 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Karim Gomaa
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configuration ={
                                           {PORT_A, PORT_PIN0, MODE_DIO, PORT_A_PIN_0_DIRECTION, PORT_A_PIN_0_RESISTOR, PORT_A_PIN_0_LEVEL, PORT_A_PIN_0_DIRECTION_CHANGABLE, PORT_A_PIN_0_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN1, MODE_DIO, PORT_A_PIN_1_DIRECTION, PORT_A_PIN_1_RESISTOR, PORT_A_PIN_1_LEVEL, PORT_A_PIN_1_DIRECTION_CHANGABLE, PORT_A_PIN_1_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN2, MODE_DIO, PORT_A_PIN_2_DIRECTION, PORT_A_PIN_2_RESISTOR, PORT_A_PIN_2_LEVEL, PORT_A_PIN_2_DIRECTION_CHANGABLE, PORT_A_PIN_2_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN3, MODE_DIO, PORT_A_PIN_3_DIRECTION, PORT_A_PIN_3_RESISTOR, PORT_A_PIN_3_LEVEL, PORT_A_PIN_3_DIRECTION_CHANGABLE, PORT_A_PIN_3_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN4, MODE_DIO, PORT_A_PIN_4_DIRECTION, PORT_A_PIN_4_RESISTOR, PORT_A_PIN_4_LEVEL, PORT_A_PIN_4_DIRECTION_CHANGABLE, PORT_A_PIN_4_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN5, MODE_DIO, PORT_A_PIN_5_DIRECTION, PORT_A_PIN_5_RESISTOR, PORT_A_PIN_5_LEVEL, PORT_A_PIN_5_DIRECTION_CHANGABLE, PORT_A_PIN_5_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN6, MODE_DIO, PORT_A_PIN_6_DIRECTION, PORT_A_PIN_6_RESISTOR, PORT_A_PIN_6_LEVEL, PORT_A_PIN_6_DIRECTION_CHANGABLE, PORT_A_PIN_6_MODE_CHANGABLE},
                                           {PORT_A, PORT_PIN7, MODE_DIO, PORT_A_PIN_7_DIRECTION, PORT_A_PIN_7_RESISTOR, PORT_A_PIN_7_LEVEL, PORT_A_PIN_7_DIRECTION_CHANGABLE, PORT_A_PIN_7_MODE_CHANGABLE},

                                           {PORT_B, PORT_PIN0, MODE_DIO, PORT_B_PIN_0_DIRECTION, PORT_B_PIN_0_RESISTOR, PORT_B_PIN_0_LEVEL, PORT_B_PIN_0_DIRECTION_CHANGABLE, PORT_B_PIN_0_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN1, MODE_DIO, PORT_B_PIN_1_DIRECTION, PORT_B_PIN_1_RESISTOR, PORT_B_PIN_1_LEVEL, PORT_B_PIN_1_DIRECTION_CHANGABLE, PORT_B_PIN_1_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN2, MODE_DIO, PORT_B_PIN_2_DIRECTION, PORT_B_PIN_2_RESISTOR, PORT_B_PIN_2_LEVEL, PORT_B_PIN_2_DIRECTION_CHANGABLE, PORT_B_PIN_2_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN3, MODE_DIO, PORT_B_PIN_3_DIRECTION, PORT_B_PIN_3_RESISTOR, PORT_B_PIN_3_LEVEL, PORT_B_PIN_3_DIRECTION_CHANGABLE, PORT_B_PIN_3_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN4, MODE_DIO, PORT_B_PIN_4_DIRECTION, PORT_B_PIN_4_RESISTOR, PORT_B_PIN_4_LEVEL, PORT_B_PIN_4_DIRECTION_CHANGABLE, PORT_B_PIN_4_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN5, MODE_DIO, PORT_B_PIN_5_DIRECTION, PORT_B_PIN_5_RESISTOR, PORT_B_PIN_5_LEVEL, PORT_B_PIN_5_DIRECTION_CHANGABLE, PORT_B_PIN_5_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN6, MODE_DIO, PORT_B_PIN_6_DIRECTION, PORT_B_PIN_6_RESISTOR, PORT_B_PIN_6_LEVEL, PORT_B_PIN_6_DIRECTION_CHANGABLE, PORT_B_PIN_6_MODE_CHANGABLE},
                                           {PORT_B, PORT_PIN7, MODE_DIO, PORT_B_PIN_7_DIRECTION, PORT_B_PIN_7_RESISTOR, PORT_B_PIN_7_LEVEL, PORT_B_PIN_7_DIRECTION_CHANGABLE, PORT_B_PIN_7_MODE_CHANGABLE},

                                           {PORT_C, PORT_PIN0, MODE_DIO, PORT_C_PIN_0_DIRECTION, PORT_C_PIN_0_RESISTOR, PORT_C_PIN_0_LEVEL, PORT_C_PIN_0_DIRECTION_CHANGABLE, PORT_C_PIN_0_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN1, MODE_DIO, PORT_C_PIN_1_DIRECTION, PORT_C_PIN_1_RESISTOR, PORT_C_PIN_1_LEVEL, PORT_C_PIN_1_DIRECTION_CHANGABLE, PORT_C_PIN_1_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN2, MODE_DIO, PORT_C_PIN_2_DIRECTION, PORT_C_PIN_2_RESISTOR, PORT_C_PIN_2_LEVEL, PORT_C_PIN_2_DIRECTION_CHANGABLE, PORT_C_PIN_2_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN3, MODE_DIO, PORT_C_PIN_3_DIRECTION, PORT_C_PIN_3_RESISTOR, PORT_C_PIN_3_LEVEL, PORT_C_PIN_3_DIRECTION_CHANGABLE, PORT_C_PIN_3_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN4, MODE_DIO, PORT_C_PIN_4_DIRECTION, PORT_C_PIN_4_RESISTOR, PORT_C_PIN_4_LEVEL, PORT_C_PIN_4_DIRECTION_CHANGABLE, PORT_C_PIN_4_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN5, MODE_DIO, PORT_C_PIN_5_DIRECTION, PORT_C_PIN_5_RESISTOR, PORT_C_PIN_5_LEVEL, PORT_C_PIN_5_DIRECTION_CHANGABLE, PORT_C_PIN_5_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN6, MODE_DIO, PORT_C_PIN_6_DIRECTION, PORT_C_PIN_6_RESISTOR, PORT_C_PIN_6_LEVEL, PORT_C_PIN_6_DIRECTION_CHANGABLE, PORT_C_PIN_6_MODE_CHANGABLE},
                                           {PORT_C, PORT_PIN7, MODE_DIO, PORT_C_PIN_7_DIRECTION, PORT_C_PIN_7_RESISTOR, PORT_C_PIN_7_LEVEL, PORT_C_PIN_7_DIRECTION_CHANGABLE, PORT_C_PIN_7_MODE_CHANGABLE},

                                           {PORT_D, PORT_PIN0, MODE_DIO, PORT_D_PIN_0_DIRECTION, PORT_D_PIN_0_RESISTOR, PORT_D_PIN_0_LEVEL, PORT_D_PIN_0_DIRECTION_CHANGABLE, PORT_D_PIN_0_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN1, MODE_DIO, PORT_D_PIN_1_DIRECTION, PORT_D_PIN_1_RESISTOR, PORT_D_PIN_1_LEVEL, PORT_D_PIN_1_DIRECTION_CHANGABLE, PORT_D_PIN_1_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN2, MODE_DIO, PORT_D_PIN_2_DIRECTION, PORT_D_PIN_2_RESISTOR, PORT_D_PIN_2_LEVEL, PORT_D_PIN_2_DIRECTION_CHANGABLE, PORT_D_PIN_2_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN3, MODE_DIO, PORT_D_PIN_3_DIRECTION, PORT_D_PIN_3_RESISTOR, PORT_D_PIN_3_LEVEL, PORT_D_PIN_3_DIRECTION_CHANGABLE, PORT_D_PIN_3_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN4, MODE_DIO, PORT_D_PIN_4_DIRECTION, PORT_D_PIN_4_RESISTOR, PORT_D_PIN_4_LEVEL, PORT_D_PIN_4_DIRECTION_CHANGABLE, PORT_D_PIN_4_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN5, MODE_DIO, PORT_D_PIN_5_DIRECTION, PORT_D_PIN_5_RESISTOR, PORT_D_PIN_5_LEVEL, PORT_D_PIN_5_DIRECTION_CHANGABLE, PORT_D_PIN_5_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN6, MODE_DIO, PORT_D_PIN_6_DIRECTION, PORT_D_PIN_6_RESISTOR, PORT_D_PIN_6_LEVEL, PORT_D_PIN_6_DIRECTION_CHANGABLE, PORT_D_PIN_6_MODE_CHANGABLE},
                                           {PORT_D, PORT_PIN7, MODE_DIO, PORT_D_PIN_7_DIRECTION, PORT_D_PIN_7_RESISTOR, PORT_D_PIN_7_LEVEL, PORT_D_PIN_7_DIRECTION_CHANGABLE, PORT_D_PIN_7_MODE_CHANGABLE},

                                           {PORT_E, PORT_PIN0, MODE_DIO, PORT_E_PIN_0_DIRECTION, PORT_E_PIN_0_RESISTOR, PORT_E_PIN_0_LEVEL, PORT_E_PIN_0_DIRECTION_CHANGABLE, PORT_E_PIN_0_MODE_CHANGABLE},
                                           {PORT_E, PORT_PIN1, MODE_DIO, PORT_E_PIN_1_DIRECTION, PORT_E_PIN_1_RESISTOR, PORT_E_PIN_1_LEVEL, PORT_E_PIN_1_DIRECTION_CHANGABLE, PORT_E_PIN_1_MODE_CHANGABLE},
                                           {PORT_E, PORT_PIN2, MODE_DIO, PORT_E_PIN_2_DIRECTION, PORT_E_PIN_2_RESISTOR, PORT_E_PIN_2_LEVEL, PORT_E_PIN_2_DIRECTION_CHANGABLE, PORT_E_PIN_2_MODE_CHANGABLE},
                                           {PORT_E, PORT_PIN3, MODE_DIO, PORT_E_PIN_3_DIRECTION, PORT_E_PIN_3_RESISTOR, PORT_E_PIN_3_LEVEL, PORT_E_PIN_3_DIRECTION_CHANGABLE, PORT_E_PIN_3_MODE_CHANGABLE},
                                           {PORT_E, PORT_PIN4, MODE_DIO, PORT_E_PIN_4_DIRECTION, PORT_E_PIN_4_RESISTOR, PORT_E_PIN_4_LEVEL, PORT_E_PIN_4_DIRECTION_CHANGABLE, PORT_E_PIN_4_MODE_CHANGABLE},
                                           {PORT_E, PORT_PIN5, MODE_DIO, PORT_E_PIN_5_DIRECTION, PORT_E_PIN_5_RESISTOR, PORT_E_PIN_5_LEVEL, PORT_E_PIN_5_DIRECTION_CHANGABLE, PORT_E_PIN_5_MODE_CHANGABLE},

                                           {PORT_F, PORT_PIN0, MODE_DIO, PORT_F_PIN_0_DIRECTION, PORT_F_PIN_0_RESISTOR, PORT_F_PIN_0_LEVEL, PORT_F_PIN_0_DIRECTION_CHANGABLE, PORT_F_PIN_0_MODE_CHANGABLE},
                                           {PORT_F, PORT_PIN1, MODE_DIO, PORT_F_PIN_1_DIRECTION, PORT_F_PIN_1_RESISTOR, PORT_F_PIN_1_LEVEL, PORT_F_PIN_1_DIRECTION_CHANGABLE, PORT_F_PIN_1_MODE_CHANGABLE},
                                           {PORT_F, PORT_PIN2, MODE_DIO, PORT_F_PIN_2_DIRECTION, PORT_F_PIN_2_RESISTOR, PORT_F_PIN_2_LEVEL, PORT_F_PIN_2_DIRECTION_CHANGABLE, PORT_F_PIN_2_MODE_CHANGABLE},
                                           {PORT_F, PORT_PIN3, MODE_DIO, PORT_F_PIN_3_DIRECTION, PORT_F_PIN_3_RESISTOR, PORT_F_PIN_3_LEVEL, PORT_F_PIN_3_DIRECTION_CHANGABLE, PORT_F_PIN_3_MODE_CHANGABLE},
                                           {PORT_F, PORT_PIN4, MODE_DIO, PORT_F_PIN_4_DIRECTION, PORT_F_PIN_4_RESISTOR, PORT_F_PIN_4_LEVEL, PORT_F_PIN_4_DIRECTION_CHANGABLE, PORT_F_PIN_4_MODE_CHANGABLE}
                                       };
