#!/usr/bin/bash

##################################################################################################### 
# 
# Auther: Karim Gomaa
#
# File Nmae: process_monitor.sh
#
# Description: Bash Script to Organize a directory, the program take a path to a directory to
#
#####################################################################################################


######################################### Main Functions ############################################

function main(){
DIRECTORY=$1

# Create sub-directories for txt, jpg, and misc files
mkdir -p "$DIRECTORY/txt"
mkdir -p "$DIRECTORY/jpg"
mkdir -p "$DIRECTORY/pdf"
mkdir -p "$DIRECTORY/misc"

# Loop through all files in the directory
for file in "$DIRECTORY"/*; do
    # Skip directories
    if [ -d "$file" ]; then
        continue
    fi

    # Get the base name of the file
    filename=$(basename -- "$file")

    # Get the file extension
    extension="${filename##*.}"

    # Handle files based on their extension
    if [ "$extension" == "txt" ]; then
        mv "$file" "$DIRECTORY/txt/"
    elif [ "$extension" == "jpg" ]; then
        mv "$file" "$DIRECTORY/jpg/"
    elif [ "$extension" == "pdf" ]; then
        mv "$file" "$DIRECTORY/pdf/"    
    else
        mv "$file" "$DIRECTORY/misc/"
    fi
done


# Loop through all hidden files in the directory
for file in "$DIRECTORY"/.*; do
    # Skip special directories . and ..
    if [ "$file" == "$DIRECTORY/." ] || [ "$file" == "$DIRECTORY/.." ]; then
        continue
    fi

    # Skip directories
    if [ -d "$file" ]; then
        continue
    fi

    # Move hidden files to misc directory
    mv "$file" "$DIRECTORY/misc/"
done

echo "Files organized successfully."
}
#####################################################################################################


# Start main $1 contain a path to a directory
main "$1"